import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qaplayground.com/bank/login');
  await page.getByTestId('login-username-input').click();
  await page.getByRole('button', { name: 'Copy username standard_user' }).click();
  await page.getByTestId('login-username-input').click();
  await page.getByTestId('login-username-input').fill('standard_user');
  await page.getByTestId('login-password-input').click();
  await page.getByRole('button', { name: 'Copy password for standard_user' }).click();
  await page.getByTestId('login-password-input').click();
  await page.getByTestId('login-password-input').fill('bank_sauce');
  await page.getByRole('button', { name: 'Show password' }).click();
  await page.getByTestId('login-remember-me-checkbox').click();
  await page.getByTestId('login-submit-btn').click();
  await page.getByTestId('quick-action-transfer').click();
  await page.getByTestId('transfer-from-select').click();
  await page.locator('[id="_r_f_"] > div').first().click();
  await page.getByTestId('transfer-from-select').click();
  await page.getByText('Everyday Checking — $').click();
  await page.getByTestId('transfer-to-select').click();
  await page.getByTestId('transfer-to-option').getByText('High-Yield Savings — $').click();
  await page.getByTestId('transfer-amount-input').click();
  await page.getByTestId('transfer-amount-input').fill('444');
  await page.getByRole('textbox', { name: 'e.g. Rent, vacation fund…' }).click();
  await page.getByRole('textbox', { name: 'e.g. Rent, vacation fund…' }).fill('4');
  await page.getByTestId('review-transfer-btn').click();
  await page.getByTestId('confirm-transfer-btn').click();
  await page.getByTestId('back-to-dashboard-btn').click();
  await page.getByTestId('sidebar-link-dashboard').click();
  await page.getByTestId('quick-action-send-money').click();
  await page.getByTestId('send-from-account-select').click();
  await page.getByText('High-Yield Savings — $').click();
  await page.getByTestId('payee-select').click();
  await page.getByText('Rahul Sharma — Chase Bank').click();
  await page.getByTestId('send-amount-input').click();
  await page.getByTestId('send-amount-input').fill('5555');
  await page.getByTestId('review-send-btn').click();
  await page.getByTestId('confirm-send-btn').click();
  await page.getByTestId('sidebar-link-dashboard').click();
  await page.getByTestId('quick-action-bill-pay').click();
  await page.getByTestId('bill-pay-from-select').click();
  await page.getByText('High-Yield Savings — $').click();
  await page.getByTestId('biller-search-input').click();
  await page.getByRole('option', { name: 'City Electric Co. Ref: ACC-' }).click();
  await page.getByTestId('bill-amount-input').click();
  await page.getByTestId('bill-amount-input').fill('4444');
  await page.getByTestId('review-bill-btn').click();
  await page.getByTestId('confirm-bill-btn').click();
  await page.getByTestId('sidebar-link-dashboard').click();
  await page.getByTestId('quick-action-apply-loan').click();
  await page.getByTestId('open-apply-loan-btn').click();
  await page.getByTestId('loan-type-select').click();
  await page.getByTestId('loan-type-select').click();
  await page.getByTestId('loan-type-options').getByText('Student').click();
  await page.getByTestId('loan-type-select').click();
  await page.getByTestId('loan-type-options').getByText('Personal').click();
  await page.getByTestId('loan-amount-input').click();
  await page.getByTestId('loan-amount-input').click();
  await page.getByTestId('loan-amount-input').click();
  await page.getByTestId('loan-amount-input').click();
  await page.getByTestId('loan-amount-input').fill('9999999999');
  await page.getByTestId('loan-term-select').click();
  await page.getByTestId('apply-loan-form').click();
  await page.getByTestId('loan-interest-rate-input').press('ArrowLeft');
  await page.getByTestId('loan-interest-rate-input').press('ArrowLeft');
  await page.getByTestId('loan-interest-rate-input').fill('4.0');
  await page.getByTestId('loan-account-select').click();
  await page.getByText('High-Yield Savings — $').click();
  await page.getByRole('textbox', { name: 'What will this loan be used' }).click();
  await page.getByRole('textbox', { name: 'What will this loan be used' }).fill('i can;t tell');
  await page.getByTestId('review-loan-btn').click();
  await page.getByTestId('review-loan-btn').click();
  await page.getByRole('textbox', { name: 'What will this loan be used' }).click();
  await page.getByRole('textbox', { name: 'What will this loan be used' }).fill('i wanna hire call girl to satisfy my needs');
  await page.getByTestId('review-loan-btn').click();
  await page.getByTestId('loan-amount-input').click();
  await page.getByTestId('loan-amount-input').fill('999');
  await page.getByTestId('review-loan-btn').click();
  await page.getByTestId('confirm-loan-btn').click();
  await page.getByTestId('sidebar-link-dashboard').click();
  await page.getByTestId('quick-action-transactions').click();
  await page.getByTestId('all-txn-account-select').click();
  await page.locator('div').filter({ hasText: /^Everyday Checking$/ }).nth(1).click();
  await page.getByTestId('all-txn-account-select').dblclick();
  await page.getByRole('option', { name: 'Everyday Checking' }).click();
  await page.getByRole('button', { name: 'Credits' }).click();
  await page.getByRole('button', { name: 'Debits' }).click();
  await page.getByTestId('clear-all-txn-filters-btn').click();
  await page.getByTestId('sidebar-link-notifications').click();
  await page.getByTestId('sidebar-link-profile').click();
  await page.getByTestId('sidebar-link-test-cases').click();
});