name: API Automated Test Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Newman
        run: sudo npm install -g newman

      - name: Run All Postman Collections Automatically
        run: |
          echo "Scanning repository for Postman collections..."
          
          find . -name "*.postman_collection.json" | while read -r collection; do
            echo "---------------------------------------------------"
            echo "Executing Collection: $collection"
            
            # Step up from 'Collections' to the parent module directory
            dir=$(dirname "$collection")
            env_file=$(find "$(dirname "$dir")" -type f -name "*.postman_environment.json" | head -n 1)
            
            if [ -n "$env_file" ]; then
              echo "Using Environment File: $env_file"
              newman run "$collection" -e "$env_file" || true
            else
              echo "No matching environment file found. Running collection standalone..."
              newman run "$collection" || true
            fi
          done