import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://automationintesting.online/');
  await page.getByRole('link', { name: 'Book Now', exact: true }).click();
  await page.getByRole('img', { name: 'Single Room' }).first().click();
  await page.getByRole('img', { name: 'Single Room' }).first().click();
  await page.getByRole('link', { name: 'Book now' }).nth(1).click();
  await page.getByRole('button', { name: 'Reserve Now' }).click();
  await page.getByRole('textbox', { name: 'Firstname' }).click();
  await page.getByRole('textbox', { name: 'Firstname' }).fill('John');
  await page.getByRole('textbox', { name: 'Lastname' }).click();
  await page.getByRole('textbox', { name: 'Lastname' }).fill('Doe');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('johndoe@example.gmail.com');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('1234567');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('1234567901');
  await page.getByRole('button', { name: 'Reserve Now' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('12345679016553');
  await page.getByRole('button', { name: 'Reserve Now' }).click();
  await page.getByRole('link', { name: 'Return home' }).click();
  await page.getByRole('link', { name: 'Book now' }).nth(2).click();
  await page.getByRole('button', { name: 'Reserve Now' }).click();
  await page.getByRole('textbox', { name: 'Firstname' }).click();
  await page.getByRole('button', { name: 'Reserve Now' }).click();
  await page.getByRole('textbox', { name: 'Firstname' }).click();
  await page.getByRole('textbox', { name: 'Firstname' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Firstname' }).fill('Joe');
  await page.getByRole('textbox', { name: 'Lastname' }).click();
  await page.getByRole('textbox', { name: 'Lastname' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Lastname' }).fill('Doe');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('doejow@oiutgmail.com');
  await page.locator('form').click();
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('4908432290855666');
  await page.getByRole('button', { name: 'Reserve Now' }).click();
  await page.getByRole('link', { name: 'Return home' }).click();
});